In [1]:
import pandas as pd
df = pd.read_csv("../data/-63-66-.csv")
df.head()

,ปีงบประมาณ,อำเภอ,รายการข้อมูล,ค่าข้อมูล,หน่วย,ที่มา
0,2563,เมืองสงขลา,รายได้จากการจำหน่ายสินค้าหนึ่งตำบล หนึ่งผลิตภั...,"745,209,437.00",บาท,กรมพัฒนาชุมชน
1,2563,สทิงพระ,รายได้จากการจำหน่ายสินค้าหนึ่งตำบล หนึ่งผลิตภั...,"440,976,250.00",บาท,กรมพัฒนาชุมชน
2,2563,จะนะ,รายได้จากการจำหน่ายสินค้าหนึ่งตำบล หนึ่งผลิตภั...,"215,216,800.00",บาท,กรมพัฒนาชุมชน
3,2563,นาทวี,รายได้จากการจำหน่ายสินค้าหนึ่งตำบล หนึ่งผลิตภั...,"204,576,591.00",บาท,กรมพัฒนาชุมชน
4,2563,เทพา,รายได้จากการจำหน่ายสินค้าหนึ่งตำบล หนึ่งผลิตภั...,"105,729,550.00",บาท,กรมพัฒนาชุมชน

In [5]:
df["ค่าข้อมูล"] = (
    df["ค่าข้อมูล"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [2]:
# ลบค่า 0
df = df[df["ค่าข้อมูล"] != 0]

# แปลงปี พ.ศ. เป็น ค.ศ.
df["ปีคริสต์ศักราช"] = df["ปีงบประมาณ"] - 543
df["ปีคริสต์ศักราช"] = pd.to_datetime(df["ปีคริสต์ศักราช"], format="%Y")

In [3]:
df_total = df.groupby("ปีคริสต์ศักราช")["ค่าข้อมูล"].sum().reset_index()
df_total = df_total.set_index("ปีคริสต์ศักราช")
df_total

                                                        ค่าข้อมูล
ปีคริสต์ศักราช
2020-01-01      745,209,437.00440,976,250.00215,216,800.00204,...
2021-01-01      735,828,505.00435,188,810.00217,523,800.00194,...
2022-01-01      118,087,760.00438,381,890.0075,172,300.0018,73...
2023-01-01      822,187,000.00511,785,905.0043,809,130.00116,1...
2024-01-01      1,061,148,000.00542,498,429.0083,905,390.00123...

In [ ]:
from sklearn.linear_model import LinearRegression

X = df_total[["ปี"]]
y = df_total["ค่าข้อมูล"]

model = LinearRegression()
model.fit(X, y)

In [8]:
y_pred = model.predict([[2025]])

NameError: name 'model' is not defined

In [ ]:
forecast = pd.DataFrame({
    "ปีงบประมาณ": [2568],
    "prediction": [y_pred[0]]
})

forecast.to_csv("../data/forecast.csv", index=False)

SyntaxError: expression expected after dictionary key and ':' (3147337122.py, line 2)

In [ ]:
forecast.to_csv("../data/forecast.csv", index=False)

NameError: name 'forecast' is not defined